// All user-facing copy for the generated pages, per language.
// Game facts mirror linhug-mobile (shared/gameRules.ts, src/localization/*). Keep them in sync.

export const SITE = "https://linhug.com";
export const APP_STORE = "https://apps.apple.com/app/id6788700503";
export const PLAY_STORE = "https://play.google.com/store/apps/details?id=com.linhug.game";
export const SUPPORT_EMAIL = "accounts@linhug.com";
export const SOCIAL = [
  { name: "TikTok", url: "https://www.tiktok.com/@linhug.game", path: "M19.59 6.69a4.83 4.83 0 0 1-3.77-3.77h-3.1v12.66a2.89 2.89 0 1 1-2-2.75V9.68a6 6 0 1 0 5.11 5.94v-6.4a7.9 7.9 0 0 0 4.65 1.5V7.65a4.85 4.85 0 0 1-.89-.96Z" },
  { name: "Instagram", url: "https://www.instagram.com/linhuggame", path: "M7.25 2h9.5A5.26 5.26 0 0 1 22 7.25v9.5A5.26 5.26 0 0 1 16.75 22h-9.5A5.26 5.26 0 0 1 2 16.75v-9.5A5.26 5.26 0 0 1 7.25 2Zm-.17 2A3.08 3.08 0 0 0 4 7.08v9.84A3.08 3.08 0 0 0 7.08 20h9.84A3.08 3.08 0 0 0 20 16.92V7.08A3.08 3.08 0 0 0 16.92 4H7.08ZM17.9 5.5a1.3 1.3 0 1 1 0 2.6 1.3 1.3 0 0 1 0-2.6ZM12 6.75A5.25 5.25 0 1 1 6.75 12 5.26 5.26 0 0 1 12 6.75Zm0 2A3.25 3.25 0 1 0 15.25 12 3.25 3.25 0 0 0 12 8.75Z" },
  { name: "LinkedIn", url: "https://www.linkedin.com/company/linhug", path: "M6.5 8.3H3.2V20h3.3V8.3ZM4.85 3A1.93 1.93 0 1 0 4.9 6.86 1.93 1.93 0 0 0 4.85 3ZM20.8 13.3c0-3.53-1.88-5.17-4.39-5.17a3.8 3.8 0 0 0-3.44 1.89V8.3H9.66V20H13v-5.8c0-1.53.29-3 2.18-3 1.86 0 1.88 1.74 1.88 3.1V20h3.31l.43-6.7Z" },
  { name: "Facebook", url: "https://www.facebook.com/people/Linhuggame/61592726338132/", path: "M13.7 21v-8h2.7l.4-3.1h-3.1v-2c0-.9.25-1.5 1.55-1.5H16.9V3.62A22.2 22.2 0 0 0 14.5 3.5c-2.38 0-4 1.45-4 4.12V9.9H7.8V13h2.7v8h3.2Z" },
];

export const SCREENSHOTS = [
  ["store-01-your-word-adventure.webp", { en: "LinHug home screen — Your Word Adventure Starts Here", tr: "LinHug ana ekranı — kelime macerası burada başlıyor", es: "Pantalla de inicio de LinHug — tu aventura de palabras empieza aquí", pt: "Tela inicial do LinHug — sua aventura de palavras começa aqui", id: "Layar beranda LinHug — petualangan katamu dimulai di sini", hi: "LinHug होम स्क्रीन — आपका शब्द रोमांच यहीं से शुरू होता है" }],
  ["store-02-find-your-room.webp", { en: "LinHug rooms screen — Find Friends and Join a Room", tr: "LinHug odalar ekranı — arkadaşlarını bul ve odaya katıl", es: "Pantalla de salas de LinHug — encuentra amigos y únete a una sala", pt: "Tela de salas do LinHug — encontre amigos e entre em uma sala", id: "Layar ruangan LinHug — temukan teman dan gabung ke ruangan", hi: "LinHug रूम स्क्रीन — दोस्तों को खोजें और रूम में जुड़ें" }],
  ["store-03-make-the-rules.webp", { en: "LinHug create room screen — Make the Rules", tr: "LinHug oda oluşturma ekranı — kuralları sen belirle", es: "Pantalla para crear sala en LinHug — tú pones las reglas", pt: "Tela de criar sala do LinHug — você define as regras", id: "Layar buat ruangan LinHug — kamu yang buat aturannya", hi: "LinHug रूम बनाने की स्क्रीन — नियम आप तय करें" }],
  ["store-04-easy-to-learn.webp", { en: "LinHug how to play screen — Easy to Learn", tr: "LinHug nasıl oynanır ekranı — öğrenmesi kolay", es: "Pantalla de cómo jugar en LinHug — fácil de aprender", pt: "Tela de como jogar do LinHug — fácil de aprender", id: "Layar cara bermain LinHug — mudah dipelajari", hi: "LinHug कैसे खेलें स्क्रीन — सीखना आसान" }],
  ["store-05-keep-words-moving.webp", { en: "LinHug gameplay screen — Keep Words Moving", tr: "LinHug oyun ekranı — kelimeler akmaya devam etsin", es: "Pantalla de juego de LinHug — que las palabras no se detengan", pt: "Tela de jogo do LinHug — mantenha as palavras em movimento", id: "Layar permainan LinHug — jaga kata terus mengalir", hi: "LinHug गेमप्ले स्क्रीन — शब्दों को चलते रहने दें" }],
  ["store-06-fair-turns-fast-fun.webp", { en: "LinHug turn order screen — Fair Turns, Fast Fun", tr: "LinHug sıra ekranı — adil sıralar, hızlı eğlence", es: "Pantalla de turnos de LinHug — turnos justos, diversión rápida", pt: "Tela de turnos do LinHug — turnos justos, diversão rápida", id: "Layar giliran LinHug — giliran adil, seru dan cepat", hi: "LinHug बारी स्क्रीन — निष्पक्ष बारी, तेज़ मज़ा" }],
  ["store-07-climb-the-scoreboard.webp", { en: "LinHug scoreboard screen — Climb the Scoreboard", tr: "LinHug skor tablosu — zirveye tırman", es: "Clasificación de LinHug — sube en la tabla", pt: "Placar do LinHug — suba no ranking", id: "Papan skor LinHug — naik ke puncak", hi: "LinHug स्कोरबोर्ड — शीर्ष पर पहुँचें" }],
];

// Language order for the switcher, hreflang alternates and the browser-language redirect.
export const LANGS = ["en", "tr", "es", "pt", "id", "hi"];

export const HUNT_POINTS = [[2, 1], [3, 1], [4, 2], [5, 4], [6, 7], [7, 11], [8, 16], [9, 22], [10, 29]];

const LEGAL_NOTICE_EN = "The LinHug name, logo, characters, graphics and audio, interface designs, text, and software are protected under applicable intellectual property laws. These materials may not be copied, adapted, distributed, extracted, or used commercially without prior written permission.";

export const copy = {
  en: {
    locale: "en_US",
    paths: { home: "/", howTo: "/how-to-play/" },
    skip: "Skip to content",
    nav: [
      ["/#modes", "Game modes"],
      ["/how-to-play/", "How to play"],
      ["/#faq", "FAQ"],
    ],
    download: "Download",
    themeLabel: "Switch between light and dark theme",
    name: "English",
    langMenu: "Choose language",
    homeAria: "LinHug home",
    navAria: "Main navigation",
    footerAria: "Footer",
    crumbAria: "Breadcrumb",
    anchors: { modes: "modes", how: "how", features: "features", screens: "screens", videos: "videos", words: "words", faq: "faq" },
    sky: ["word", "magic", "dream", "ocean", "spark", "castle", "echo", "play"],
    app: { alternateName: "LinHug Word Chain", genre: "Word game" },
    aside: { title: "Get LinHug", text: "Play live word chain with your friends. Free." },
    footer: {
      rights: "© 2026 LinHug. All rights reserved.",
      social: "Follow LinHug on social media",
      followOn: (name) => `Follow LinHug on ${name}`,
      links: [["/how-to-play/", "How to play"], ["/privacy.html", "Privacy Policy"], ["/terms.html", "Terms of Use"], [`mailto:${SUPPORT_EMAIL}`, "Support"]],
      notice: LEGAL_NOTICE_EN,
    },
    badges: { apple: "Download on the App Store", google: "Get it on Google Play", appleAria: "Download LinHug on the App Store", googleAria: "Get LinHug on Google Play" },
    home: {
      title: "Word Chain Game with Friends — LinHug for iPhone & Android",
      description: "LinHug is a free multiplayer word chain game. Create a room, invite friends and follow the last letter in English or Turkish. Download for iOS and Android.",
      kicker: "Live multiplayer word battles",
      h1: "Word chain game.",
      h1Accent: "Keep the chain alive.",
      intro: "LinHug is a free multiplayer word game for iPhone and Android. Create a room, invite your friends and turn the last letter of every word into your next move. Play Classic Chain, Word Battle or Letter Hunt with English or Turkish words.",
      meta: ["Free to play", "iOS & Android", "English & Turkish words"],
      reelAria: "LinHug mascot completing the logo",
      reelBadge: "Meet LinHug",
      modesTitle: "Three ways to play.",
      modesLead: "Every room picks a mode, a word language and a timer. Start calm, end in a photo finish.",
      modes: [
        { icon: "∞", title: "Classic Chain", text: "The original word chain. Each word must start with the last letter of the previous one. Run out of time and you are out; the last player standing earns a +20 survival bonus.", tag: "Turn based" },
        { icon: "⚡", title: "Word Battle", text: "Everyone answers the same letter challenge in the same round. Send one valid, unique word before the timer ends; longer words score more.", tag: "Everyone plays" },
        { icon: "★", title: "Letter Hunt", text: "Everyone gets the same 8, then 9, then 10 letter tiles. Find as many words as you can in three 45-second rounds. Long words are worth big points.", tag: "3 rounds · 45 seconds" },
      ],
      chainTitle: "How a word chain works.",
      chainLead: "One rule keeps the game moving: your word starts where the last one ended.",
      chain: ["appl<b>e</b>", "elephan<b>t</b>", "tige<b>r</b>", "rocke<b>t</b>", "train"],
      steps: [
        ["Create or join a room", "Open a public room, or make a private one and share the invite code with friends."],
        ["Follow the last letter", "Your word must start with the final letter of the previous word, and it must be in the dictionary."],
        ["Beat the timer", "Think fast. Repeated words are rejected and the clock keeps ticking."],
        ["Climb the scoreboard", "Every letter counts. Win rounds, collect points and rise up the leaderboard."],
      ],
      howToLink: "Read the full rules →",
      featuresTitle: "A word game built for friends.",
      featuresLead: "Simple to start, hard to put down. Every room creates a new chain and every second matters.",
      features: [
        { icon: "⌂", title: "Private rooms", text: "Create a private room and share a code. Your friends join from Rooms → Join room with code." },
        { icon: "☺", title: "Your avatar, your style", text: "Pick an avatar and a room background, then bring your personality into every match." },
        { icon: "◎", title: "Play as a guest", text: "No sign-up needed. Optionally sign in with Apple or Google to keep your progress on a new device." },
      ],
      screensTitle: "Your word adventure, at a glance.",
      screensLead: "Find a room, make the rules, learn the chain, and race your friends to the top of the scoreboard.",
      screensAria: "LinHug app screenshots",
      prev: "Show previous app screenshot",
      next: "Show next app screenshot",
      swipe: "Swipe or use the arrows to explore",
      videosTitle: "See LinHug in motion.",
      videosLead: "Quick rounds, surprising words, and the playful energy of keeping the chain alive.",
      videos: [
        ["linhug-gameplay", "Play together", "Invite your friends and turn every round into a fast multiplayer challenge."],
        ["linhug-word-chain", "Keep the words flowing", "Think quickly, follow the last letter, and keep the chain moving before time runs out."],
        ["linhug-avatar", "Meet your avatar", "Choose your style and bring your own personality into every LinHug room."],
        ["linhug-rocket", "Launch into the game", "Jump into a room, start the challenge, and keep your word streak moving."],
      ],
      faqTitle: "Frequently asked questions",
      faq: [
        ["What is LinHug?", "LinHug is a free multiplayer word chain game for iPhone, iPad and Android. You play live against friends or other players in rooms, taking turns to keep a chain of words going."],
        ["How do you play a word chain game?", "Each player says a word that starts with the last letter of the previous word. For example: apple → elephant → tiger. Words cannot be repeated, they must be real dictionary words, and you have to answer before the timer runs out. See the <a href=\"/how-to-play/\">full rules</a>."],
        ["Is LinHug free?", "Yes. LinHug is free to download and play on the App Store and Google Play."],
        ["Can I play privately with friends?", "Yes. Create a private room and share its invite code. Friends open Rooms → Join room with code and enter it to join you."],
        ["Which languages can I play in?", "Each room chooses its word language: English or Turkish. The app interface is available in English, Turkish, Spanish, Portuguese, Indonesian and Hindi."],
        ["Do I need an account?", "No. You can play as a guest right away. If you want to keep your progress on another device, you can optionally sign in with Apple or Google."],
        ["What is Letter Hunt?", "Letter Hunt is an anagram-style mode. Everyone gets the same letter tiles (8, then 9, then 10) and has 45 seconds per round to find as many words as possible. Longer words earn far more points."],
      ],
      ctaTitle: "Your next word starts here.",
      ctaText: "Bring your friends together and see how long you can keep the chain alive.",
      ctaIcon: "LinHug app icon",
    },
    howTo: {
      title: "How to Play Word Chain — LinHug Rules & Game Modes",
      description: "Learn the word chain rules: start with the last letter, beat the timer and never repeat a word. Plus Word Battle and Letter Hunt scoring in LinHug.",
      crumbs: [["/", "Home"], [null, "How to play"]],
      h1: "How to play word chain",
      lead: "Word chain (also called the last letter game or word snake) is a classic word game: every new word has to begin with the last letter of the word before it. LinHug turns it into a live multiplayer game with a timer, three modes and a dictionary that checks every word.",
      sections: [
        ["The basic rule", [
          "<p>The first player gets a starting letter. Every following word must start with the <strong>last letter of the previous word</strong>:</p>",
          "<p class=\"callout\"><strong>apple → elephant → tiger → rocket → train</strong></p>",
          "<ul><li>Words must be in the room’s dictionary (English or Turkish).</li><li>A word can only be used once per game.</li><li>You must answer before the round timer ends.</li><li>Proper names and abbreviations do not count.</li></ul>",
        ]],
        ["Classic Chain", [
          "<p>Players take turns in order. Each valid word scores <strong>one point per letter</strong>, so longer words help you pull ahead. If your timer runs out, you are out of the round. The last player standing receives a <strong>+20 survival bonus</strong>, and the highest total score wins.</p>",
          "<p>Tip: words that end with rare letters (like <em>x</em>) put pressure on the next player. When a word ends in <em>x</em>, the next player may start with any letter.</p>",
        ]],
        ["Word Battle", [
          "<p>Everyone plays at the same time. Each round shows one letter challenge, and every player sends <strong>one valid, unique word</strong> that starts with that letter before the timer ends. Points are based on word length, so a long, rare word beats a quick short one.</p>",
        ]],
        ["Letter Hunt", [
          "<p>All players receive the same letter tiles: <strong>8 in round one, 9 in round two and 10 in round three</strong>. Tap tiles to build words (each tile once per word) and send as many different words as you can in <strong>45 seconds</strong>. Opponents’ words stay hidden until the round ends.</p>",
          "@@HUNT_TABLE@@",
          "<p>The highest total after three rounds wins. Ties share the win.</p>",
        ]],
        ["Rooms, friends and bots", [
          "<p>Join a public room from the Rooms screen, or create your own and choose the mode, word language, room size, round time and visibility. Private rooms get an invite code you can share. LinHug also keeps open Letter Hunt lobbies with friendly bots, so there is always a game to jump into.</p>",
        ]],
        ["Tips to win", [
          "<ul><li>Learn words that end with tricky letters to trap the next player.</li><li>Save a few long words for each letter: they are worth more points.</li><li>In Letter Hunt, look for common endings first, then rearrange them into longer words.</li><li>Do not panic: a short valid word is better than running out of time.</li></ul>",
        ]],
      ],
      huntTable: ["Word length", "Points"],
    },
    notFound: { title: "Page not found — LinHug", h1: "This chain is broken.", text: "We couldn’t find that page. Head back home and start a new word.", button: "Back to LinHug" },
  },

  tr: {
    locale: "tr_TR",
    paths: { home: "/tr/", howTo: "/tr/nasil-oynanir/" },
    skip: "İçeriğe geç",
    nav: [
      ["/tr/#modlar", "Oyun modları"],
      ["/tr/nasil-oynanir/", "Nasıl oynanır"],
      ["/tr/kelimeler/", "Kelime listeleri"],
    ],
    download: "İndir",
    themeLabel: "Açık ve koyu tema arasında geçiş yap",
    name: "Türkçe",
    langMenu: "Dil seç",
    homeAria: "LinHug ana sayfa",
    navAria: "Ana menü",
    footerAria: "Alt menü",
    crumbAria: "Sayfa yolu",
    anchors: { modes: "modlar", how: "nasil", features: "ozellikler", screens: "ekranlar", videos: "videolar", words: "kelimeler", faq: "sss" },
    sky: ["kelime", "zincir", "harf", "kalem", "masa", "yıldız", "renk", "oyun"],
    app: { alternateName: "LinHug Kelime Zinciri", genre: "Kelime oyunu" },
    aside: { title: "LinHug’ı indir", text: "Arkadaşlarınla canlı kelime zinciri oyna. Ücretsiz." },
    footer: {
      rights: "© 2026 LinHug. Tüm hakları saklıdır.",
      social: "LinHug’ı sosyal medyada takip et",
      followOn: (name) => `LinHug’ı ${name}’da takip et`,
      links: [["/tr/nasil-oynanir/", "Nasıl oynanır"], ["/tr/kelimeler/", "Kelime listeleri"], ["/privacy.html", "Gizlilik Politikası"], ["/terms.html", "Kullanım Koşulları"], [`mailto:${SUPPORT_EMAIL}`, "Destek"]],
      notice: "LinHug adı, logosu, karakterleri, grafik ve sesleri, arayüz tasarımları, metinleri ve yazılımı ilgili fikri mülkiyet yasalarıyla korunmaktadır. Bu materyaller önceden yazılı izin alınmadan kopyalanamaz, uyarlanamaz, dağıtılamaz, çıkarılamaz veya ticari amaçla kullanılamaz.",
    },
    badges: { apple: "App Store’dan indir", google: "Google Play’den alın", appleAria: "LinHug’ı App Store’dan indir", googleAria: "LinHug’ı Google Play’den indir" },
    home: {
      title: "Kelime Zinciri Oyunu — Arkadaşlarınla Online Kelime Oyunu | LinHug",
      description: "LinHug ücretsiz, çok oyunculu bir kelime oyunu. Oda kur, arkadaşlarını davet et, son harften kelime türet. iPhone ve Android’de Türkçe kelimelerle oyna.",
      kicker: "Canlı, çok oyunculu kelime düelloları",
      h1: "Kelime zinciri oyunu.",
      h1Accent: "Zinciri koparma!",
      intro: "LinHug, iPhone ve Android için ücretsiz, çok oyunculu bir kelime oyunu. Bir oda kur, arkadaşlarını davet et ve her kelimenin son harfinden yeni bir kelime türet. Klasik Zincir, Kelime Düellosu ve Harf Avı modlarını Türkçe ya da İngilizce kelimelerle oyna.",
      meta: ["Ücretsiz", "iOS ve Android", "Türkçe ve İngilizce kelimeler"],
      reelAria: "LinHug maskotu logoyu tamamlıyor",
      reelBadge: "LinHug ile tanış",
      modesTitle: "Üç farklı oyun modu.",
      modesLead: "Her oda bir mod, bir kelime dili ve bir süre seçer. Sakin başlar, nefes kesen bir finalle biter.",
      modes: [
        { icon: "∞", title: "Klasik Zincir", text: "Bildiğin kelime türetmece. Her kelime, bir önceki kelimenin son harfiyle başlamalı. Süren biterse elenirsin; ayakta kalan son oyuncu +20 hayatta kalma bonusu kazanır.", tag: "Sıralı tur" },
        { icon: "⚡", title: "Kelime Düellosu", text: "Herkes aynı turda aynı harf meydan okumasına cevap verir. Süre bitmeden geçerli ve benzersiz bir kelime gönder; uzun kelimeler daha çok puan getirir.", tag: "Herkes oynar" },
        { icon: "★", title: "Harf Avı", text: "Herkese aynı harf taşları verilir: önce 8, sonra 9, sonra 10. 45 saniyelik üç turda bulabildiğin kadar kelime bul. Uzun kelimeler çok daha fazla puan getirir.", tag: "3 tur · 45 saniye" },
      ],
      chainTitle: "Kelime zinciri nasıl işler?",
      chainLead: "Oyunu tek bir kural döndürür: senin kelimen, öncekinin bittiği harfle başlar.",
      chain: ["kale<b>m</b>", "mas<b>a</b>", "arab<b>a</b>", "anahta<b>r</b>", "renk"],
      steps: [
        ["Oda kur ya da katıl", "Herkese açık bir odaya gir veya özel oda kurup davet kodunu arkadaşlarınla paylaş."],
        ["Son harfi takip et", "Kelimen bir önceki kelimenin son harfiyle başlamalı ve sözlükte bulunmalı."],
        ["Süreyi yen", "Hızlı düşün. Daha önce yazılan kelimeler kabul edilmez, saat de durmaz."],
        ["Skor tablosunda yüksel", "Her harf puan demek. Turları kazan, puan topla, sıralamada yüksel."],
      ],
      howToLink: "Tüm kuralları oku →",
      featuresTitle: "Arkadaşlarla oynamak için tasarlandı.",
      featuresLead: "Başlaması kolay, bırakması zor. Her odada yeni bir zincir kurulur ve her saniye önemlidir.",
      features: [
        { icon: "⌂", title: "Özel odalar", text: "Özel bir oda kur ve kodu paylaş. Arkadaşların Odalar → Kodla odaya katıl bölümünden sana katılır." },
        { icon: "☺", title: "Avatarın, tarzın", text: "Bir avatar ve oda arka planı seç, her maça kendi tarzını getir." },
        { icon: "◎", title: "Misafir olarak oyna", text: "Üyelik gerekmez. İstersen Apple veya Google ile giriş yaparak ilerlemeni yeni bir cihaza taşıyabilirsin." },
      ],
      screensTitle: "Kelime maceran, tek bakışta.",
      screensLead: "Oda bul, kuralları belirle, zinciri öğren ve skor tablosunun zirvesine arkadaşlarınla yarış.",
      screensAria: "LinHug uygulama ekran görüntüleri",
      prev: "Önceki ekran görüntüsünü göster",
      next: "Sonraki ekran görüntüsünü göster",
      swipe: "Kaydır ya da okları kullan",
      videosTitle: "LinHug’ı hareket halinde gör.",
      videosLead: "Hızlı turlar, şaşırtıcı kelimeler ve zinciri ayakta tutmanın keyfi.",
      videos: [
        ["linhug-gameplay", "Birlikte oyna", "Arkadaşlarını davet et, her turu hızlı bir çok oyunculu yarışa dönüştür."],
        ["linhug-word-chain", "Kelimeler aksın", "Hızlı düşün, son harfi takip et ve süre bitmeden zinciri devam ettir."],
        ["linhug-avatar", "Avatarınla tanış", "Tarzını seç ve her LinHug odasına kendi kişiliğini getir."],
        ["linhug-rocket", "Oyuna fırla", "Bir odaya gir, meydan okumayı başlat ve kelime serini sürdür."],
      ],
      wordsTitle: "Zincirde takıldın mı?",
      wordsText: "Rakibin “ğ” ile biten bir kelime mi yazdı, yoksa aklına “j” ile başlayan kelime mi gelmiyor? LinHug’ın Türkçe sözlüğünden hazırlanan kelime listelerine göz at: harfe göre başlayan ve biten kelimeler, harf sayısına göre kelimeler.",
      wordsLink: "Tüm kelime listeleri →",
      faqTitle: "Sıkça sorulan sorular",
      faq: [
        ["LinHug nedir?", "LinHug, iPhone, iPad ve Android için ücretsiz, çok oyunculu bir kelime zinciri oyunudur. Odalarda arkadaşlarınla ya da diğer oyuncularla canlı oynar, sırayla kelime türeterek zinciri devam ettirirsin."],
        ["Kelime zinciri oyunu nasıl oynanır?", "Her oyuncu, bir önceki kelimenin son harfiyle başlayan yeni bir kelime söyler. Örneğin: kalem → masa → araba. Aynı kelime iki kez kullanılamaz, kelime sözlükte olmalıdır ve süre bitmeden cevap verilmelidir. Ayrıntılar için <a href=\"/tr/nasil-oynanir/\">nasıl oynanır</a> sayfasına bak."],
        ["LinHug ücretsiz mi?", "Evet. LinHug’ı App Store ve Google Play’den ücretsiz indirip oynayabilirsin."],
        ["Türkçe kelimelerle oynayabilir miyim?", "Evet. Oda kurarken kelime dili olarak Türkçeyi seç. Türkçe sözlükte 38.000’den fazla kelime var; uygulamanın arayüzü de tamamen Türkçe."],
        ["Hangi kelimeler geçerli sayılır?", "Sözlükteki kelimelerin yalın halleri geçerlidir. Özel isimler, kısaltmalar ve çekimli biçimler (ör. “kitaplar”, “evde”) kabul edilmez."],
        ["“ğ” ile biten kelime yazılırsa ne olur?", "Türkçede “ğ” ile başlayan kelime olmadığı için, “ğ” ile biten bir kelimeden (ör. dağ, bağ) sonra sıradaki oyuncu istediği harfle başlayabilir. <a href=\"/tr/kelimeler/ğ-ile-biten-kelimeler/\">ğ ile biten kelimeler</a> listesine göz at."],
        ["Arkadaşlarımla özel oda kurabilir miyim?", "Evet. Özel oda kur ve davet kodunu paylaş. Arkadaşların Odalar → Kodla odaya katıl bölümüne kodu girerek katılır."],
        ["Hesap açmam gerekiyor mu?", "Hayır. Hemen misafir olarak oynayabilirsin. İlerlemeni başka bir cihazda sürdürmek istersen isteğe bağlı olarak Apple veya Google ile giriş yapabilirsin."],
      ],
      ctaTitle: "Sıradaki kelime seni bekliyor.",
      ctaText: "Arkadaşlarını topla ve zinciri ne kadar uzun süre ayakta tutabileceğinizi görün.",
      ctaIcon: "LinHug uygulama simgesi",
    },
    howTo: {
      title: "Kelime Zinciri Nasıl Oynanır? Kurallar ve Oyun Modları | LinHug",
      description: "Kelime zinciri (kelime türetmece) kuralları: son harfle başla, süreyi kaçırma, aynı kelimeyi tekrarlama. Kelime Düellosu ve Harf Avı puanlaması.",
      crumbs: [["/tr/", "Ana sayfa"], [null, "Nasıl oynanır"]],
      h1: "Kelime zinciri nasıl oynanır?",
      lead: "Kelime zinciri (kelime türetmece, son harf oyunu) klasik bir kelime oyunudur: her yeni kelime, bir önceki kelimenin son harfiyle başlamak zorundadır. LinHug bu oyunu süre sınırı, üç farklı mod ve her kelimeyi kontrol eden bir sözlükle canlı, çok oyunculu bir oyuna dönüştürür.",
      sections: [
        ["Temel kural", [
          "<p>İlk oyuncuya bir başlangıç harfi verilir. Sonraki her kelime, <strong>bir önceki kelimenin son harfiyle</strong> başlamalıdır:</p>",
          "<p class=\"callout\"><strong>kalem → masa → araba → anahtar → renk</strong></p>",
          "<ul><li>Kelime, odanın sözlüğünde (Türkçe veya İngilizce) bulunmalıdır.</li><li>Bir kelime aynı oyunda yalnızca bir kez kullanılabilir.</li><li>Tur süresi bitmeden cevap vermelisin.</li><li>Özel isimler, kısaltmalar ve çekimli biçimler (ör. “evler”, “okulda”) geçerli değildir.</li></ul>",
        ]],
        ["Klasik Zincir", [
          "<p>Oyuncular sırayla oynar. Her geçerli kelime <strong>harf sayısı kadar puan</strong> kazandırır, yani uzun kelimeler seni öne geçirir. Süren biterse turdan elenirsin. Ayakta kalan son oyuncu <strong>+20 hayatta kalma bonusu</strong> alır ve en yüksek toplam puan oyunu kazanır.</p>",
          "<p>“ğ” ile biten bir kelime yazılırsa (ör. <em>dağ</em>, <em>yağ</em>), Türkçede “ğ” ile başlayan kelime olmadığı için sıradaki oyuncu <strong>istediği harfle</strong> başlayabilir. <a href=\"/tr/kelimeler/ğ-ile-biten-kelimeler/\">ğ ile biten kelimeler</a> listesine göz at.</p>",
        ]],
        ["Kelime Düellosu", [
          "<p>Herkes aynı anda oynar. Her turda bir harf meydan okuması çıkar ve her oyuncu süre bitmeden o harfle başlayan <strong>geçerli ve benzersiz bir kelime</strong> gönderir. Puan kelime uzunluğuna göre hesaplanır; uzun ve az bilinen bir kelime, hızlı yazılmış kısa bir kelimeyi yener.</p>",
        ]],
        ["Harf Avı", [
          "<p>Bütün oyunculara aynı harf taşları verilir: <strong>birinci turda 8, ikincide 9, üçüncüde 10</strong>. Taşlara dokunarak kelime oluştur (her taş bir kelimede bir kez kullanılır) ve <strong>45 saniyede</strong> bulabildiğin kadar farklı kelime gönder. Rakiplerin kelimeleri tur bitene kadar gizli kalır.</p>",
          "@@HUNT_TABLE@@",
          "<p>Üç tur sonunda en yüksek puanı toplayan kazanır. Eşitlikte galibiyet paylaşılır.</p>",
        ]],
        ["Odalar, arkadaşlar ve botlar", [
          "<p>Odalar ekranından herkese açık bir odaya katıl ya da kendi odanı kurup modu, kelime dilini, oda boyutunu, tur süresini ve görünürlüğü seç. Özel odalara paylaşabileceğin bir davet kodu verilir. LinHug’da her zaman açık, botlu Harf Avı odaları da bulunur; böylece katılabileceğin bir oyun hep vardır.</p>",
        ]],
        ["Kazanmak için ipuçları", [
          "<ul><li>Rakibini zorlayan harflerle biten kelimeler öğren; örneğin <a href=\"/tr/kelimeler/j-ile-biten-kelimeler/\">j ile biten</a> ya da <a href=\"/tr/kelimeler/f-ile-biten-kelimeler/\">f ile biten</a> kelimeler.</li><li>Her harf için birkaç uzun kelime aklında olsun; uzun kelimeler daha çok puan getirir.</li><li>Harf Avı’nda önce yaygın ekleri ve hecelerini bul, sonra onları daha uzun kelimelere dönüştür.</li><li>Panik yapma: kısa ama geçerli bir kelime, sürenin bitmesinden iyidir.</li></ul>",
          "<p>Takıldığın harfler için <a href=\"/tr/kelimeler/\">Türkçe kelime listelerine</a> göz at.</p>",
        ]],
      ],
      huntTable: ["Kelime uzunluğu", "Puan"],
    },
    notFound: { title: "Sayfa bulunamadı — LinHug", h1: "Bu zincir koptu.", text: "Aradığın sayfayı bulamadık. Ana sayfaya dönüp yeni bir kelimeyle başla.", button: "LinHug’a dön" },
  },
  es: {
    locale: "es_MX",
    paths: { home: "/es/", howTo: "/es/como-jugar/" },
    skip: "Saltar al contenido",
    nav: [
      ["/es/#modos", "Modos de juego"],
      ["/es/como-jugar/", "Cómo jugar"],
      ["/es/#preguntas", "Preguntas"],
    ],
    download: "Descargar",
    themeLabel: "Cambiar entre tema claro y oscuro",
    name: "Español",
    langMenu: "Elegir idioma",
    homeAria: "Inicio de LinHug",
    navAria: "Navegación principal",
    footerAria: "Pie de página",
    crumbAria: "Ruta de navegación",
    anchors: { modes: "modos", how: "como", features: "funciones", screens: "pantallas", videos: "videos", words: "palabras", faq: "preguntas" },
    sky: ["palabra", "magia", "sueño", "océano", "chispa", "castillo", "eco", "jugar"],
    app: { alternateName: "LinHug Cadena de Palabras", genre: "Juego de palabras" },
    aside: { title: "Descarga LinHug", text: "Juega cadena de palabras en vivo con tus amigos. Gratis." },
    footer: {
      rights: "© 2026 LinHug. Todos los derechos reservados.",
      social: "Sigue a LinHug en redes sociales",
      followOn: (name) => `Sigue a LinHug en ${name}`,
      links: [["/es/como-jugar/", "Cómo jugar"], ["/privacy.html", "Política de privacidad"], ["/terms.html", "Términos de uso"], [`mailto:${SUPPORT_EMAIL}`, "Soporte"]],
      notice: "El nombre, el logotipo, los personajes, los gráficos y el audio, los diseños de interfaz, los textos y el software de LinHug están protegidos por las leyes de propiedad intelectual aplicables. Estos materiales no pueden copiarse, adaptarse, distribuirse, extraerse ni usarse con fines comerciales sin autorización previa por escrito.",
    },
    badges: { apple: "Descárgalo en el App Store", google: "Disponible en Google Play", appleAria: "Descarga LinHug en el App Store", googleAria: "Descarga LinHug en Google Play" },
    home: {
      title: "Juego de Cadena de Palabras con Amigos — LinHug para iPhone y Android",
      description: "LinHug es un juego gratuito y multijugador de cadena de palabras. Crea una sala, invita a tus amigos y sigue la última letra. Descárgalo para iOS y Android.",
      kicker: "Batallas de palabras multijugador en vivo",
      h1: "Juego de cadena de palabras.",
      h1Accent: "Que la cadena no se rompa.",
      intro: "LinHug es un juego de palabras gratuito y multijugador para iPhone y Android. Crea una sala, invita a tus amigos y convierte la última letra de cada palabra en tu siguiente jugada. Juega Cadena clásica, Batalla de palabras o Caza de letras con palabras en inglés o turco, con la app completamente en español.",
      meta: ["Gratis", "iOS y Android", "App en español"],
      reelAria: "La mascota de LinHug completando el logotipo",
      reelBadge: "Conoce a LinHug",
      modesTitle: "Tres formas de jugar.",
      modesLead: "Cada sala elige un modo, un idioma de palabras y un temporizador. Empieza tranquilo y termina en un final de foto.",
      modes: [
        { icon: "∞", title: "Cadena clásica", text: "La cadena de palabras de siempre. Cada palabra debe empezar con la última letra de la anterior. Si se te acaba el tiempo, quedas fuera; el último jugador en pie gana un bono de supervivencia de +20.", tag: "Por turnos" },
        { icon: "⚡", title: "Batalla de palabras", text: "Todos responden al mismo reto de letra en la misma ronda. Envía una palabra válida y única antes de que termine el tiempo; las palabras más largas suman más puntos.", tag: "Todos juegan" },
        { icon: "★", title: "Caza de letras", text: "Todos reciben las mismas fichas: 8, luego 9 y luego 10 letras. Encuentra todas las palabras que puedas en tres rondas de 45 segundos. Las palabras largas valen muchos puntos.", tag: "3 rondas · 45 segundos" },
      ],
      chainTitle: "Cómo funciona una cadena de palabras.",
      chainLead: "Una sola regla mantiene el juego en marcha: tu palabra empieza donde terminó la anterior.",
      chain: ["appl<b>e</b>", "elephan<b>t</b>", "tige<b>r</b>", "rocke<b>t</b>", "train"],
      steps: [
        ["Crea o únete a una sala", "Entra a una sala pública o crea una privada y comparte el código de invitación con tus amigos."],
        ["Sigue la última letra", "Tu palabra debe empezar con la última letra de la palabra anterior y debe estar en el diccionario."],
        ["Gánale al reloj", "Piensa rápido. Las palabras repetidas se rechazan y el reloj no se detiene."],
        ["Sube en la clasificación", "Cada letra cuenta. Gana rondas, suma puntos y escala en la tabla."],
      ],
      howToLink: "Lee todas las reglas →",
      featuresTitle: "Un juego de palabras hecho para amigos.",
      featuresLead: "Fácil de empezar, difícil de soltar. Cada sala crea una cadena nueva y cada segundo cuenta.",
      features: [
        { icon: "⌂", title: "Salas privadas", text: "Crea una sala privada y comparte el código. Tus amigos se unen desde Salas → Unirse con código." },
        { icon: "☺", title: "Tu avatar, tu estilo", text: "Elige un avatar y un fondo de sala, y lleva tu personalidad a cada partida." },
        { icon: "◎", title: "Juega como invitado", text: "No necesitas registrarte. Si quieres, inicia sesión con Apple o Google para conservar tu progreso en otro dispositivo." },
      ],
      screensTitle: "Tu aventura de palabras, de un vistazo.",
      screensLead: "Encuentra una sala, pon las reglas, aprende la cadena y compite con tus amigos por la cima de la clasificación.",
      screensAria: "Capturas de pantalla de la app LinHug",
      prev: "Mostrar la captura anterior",
      next: "Mostrar la siguiente captura",
      swipe: "Desliza o usa las flechas para explorar",
      videosTitle: "Mira LinHug en acción.",
      videosLead: "Rondas rápidas, palabras sorprendentes y la energía de mantener viva la cadena.",
      videos: [
        ["linhug-gameplay", "Jueguen juntos", "Invita a tus amigos y convierte cada ronda en un reto multijugador rápido."],
        ["linhug-word-chain", "Que fluyan las palabras", "Piensa rápido, sigue la última letra y mantén la cadena antes de que se acabe el tiempo."],
        ["linhug-avatar", "Conoce a tu avatar", "Elige tu estilo y lleva tu personalidad a cada sala de LinHug."],
        ["linhug-rocket", "Despega al juego", "Entra a una sala, empieza el reto y mantén tu racha de palabras."],
      ],
      faqTitle: "Preguntas frecuentes",
      faq: [
        ["¿Qué es LinHug?", "LinHug es un juego gratuito y multijugador de cadena de palabras para iPhone, iPad y Android. Juegas en vivo contra amigos u otros jugadores en salas, por turnos, para mantener viva una cadena de palabras."],
        ["¿Cómo se juega a la cadena de palabras?", "Cada jugador dice una palabra que empieza con la última letra de la palabra anterior. Por ejemplo: apple → elephant → tiger. No se pueden repetir palabras, deben estar en el diccionario y hay que responder antes de que se acabe el tiempo. Consulta las <a href=\"/es/como-jugar/\">reglas completas</a>."],
        ["¿LinHug es gratis?", "Sí. LinHug se descarga y se juega gratis en el App Store y en Google Play."],
        ["¿En qué idiomas puedo jugar?", "Cada sala elige el idioma de las palabras: inglés o turco. La app está disponible en español, inglés, turco, portugués, indonesio e hindi."],
        ["¿Puedo jugar en privado con amigos?", "Sí. Crea una sala privada y comparte su código de invitación. Tus amigos abren Salas → Unirse con código y lo ingresan para unirse."],
        ["¿Necesito una cuenta?", "No. Puedes jugar como invitado de inmediato. Si quieres conservar tu progreso en otro dispositivo, puedes iniciar sesión con Apple o Google."],
        ["¿Qué es Caza de letras?", "Caza de letras es un modo tipo anagrama. Todos reciben las mismas fichas de letras (8, luego 9 y luego 10) y tienen 45 segundos por ronda para encontrar todas las palabras posibles. Las palabras largas dan muchos más puntos."],
      ],
      ctaTitle: "Tu próxima palabra empieza aquí.",
      ctaText: "Reúne a tus amigos y descubre cuánto tiempo pueden mantener viva la cadena.",
      ctaIcon: "Icono de la app LinHug",
    },
    howTo: {
      title: "Cómo Jugar a la Cadena de Palabras — Reglas y Modos de LinHug",
      description: "Aprende las reglas de la cadena de palabras: empieza con la última letra, gánale al reloj y no repitas palabras. Además, puntos de Batalla de palabras y Caza de letras.",
      crumbs: [["/es/", "Inicio"], [null, "Cómo jugar"]],
      h1: "Cómo jugar a la cadena de palabras",
      lead: "La cadena de palabras (también llamada juego de la última letra) es un clásico: cada palabra nueva debe empezar con la última letra de la anterior. LinHug lo convierte en un juego multijugador en vivo con temporizador, tres modos y un diccionario que revisa cada palabra.",
      sections: [
        ["La regla básica", [
          "<p>El primer jugador recibe una letra inicial. Cada palabra siguiente debe empezar con la <strong>última letra de la palabra anterior</strong>:</p>",
          "<p class=\"callout\"><strong>apple → elephant → tiger → rocket → train</strong></p>",
          "<ul><li>Las palabras deben estar en el diccionario de la sala (inglés o turco).</li><li>Cada palabra solo se puede usar una vez por partida.</li><li>Debes responder antes de que termine el tiempo de la ronda.</li><li>Los nombres propios y las abreviaturas no cuentan.</li></ul>",
        ]],
        ["Cadena clásica", [
          "<p>Los jugadores juegan por turnos. Cada palabra válida suma <strong>un punto por letra</strong>, así que las palabras largas te ponen adelante. Si se te acaba el tiempo, quedas fuera de la ronda. El último jugador en pie recibe un <strong>bono de supervivencia de +20</strong> y gana el puntaje total más alto.</p>",
          "<p>Consejo: las palabras que terminan en letras raras (como la <em>x</em>) presionan al siguiente jugador. Cuando una palabra termina en <em>x</em>, el siguiente jugador puede empezar con cualquier letra.</p>",
        ]],
        ["Batalla de palabras", [
          "<p>Todos juegan al mismo tiempo. Cada ronda muestra un reto de letra y cada jugador envía <strong>una palabra válida y única</strong> que empiece con esa letra antes de que termine el tiempo. Los puntos dependen de la longitud, así que una palabra larga y poco común le gana a una corta y rápida.</p>",
        ]],
        ["Caza de letras", [
          "<p>Todos los jugadores reciben las mismas fichas: <strong>8 en la primera ronda, 9 en la segunda y 10 en la tercera</strong>. Toca las fichas para formar palabras (cada ficha una vez por palabra) y envía todas las palabras distintas que puedas en <strong>45 segundos</strong>. Las palabras de los rivales se ocultan hasta que termina la ronda.</p>",
          "@@HUNT_TABLE@@",
          "<p>Gana quien tenga más puntos después de tres rondas. En caso de empate, se comparte la victoria.</p>",
        ]],
        ["Salas, amigos y bots", [
          "<p>Únete a una sala pública desde la pantalla Salas o crea la tuya y elige el modo, el idioma de las palabras, el tamaño de la sala, el tiempo de ronda y la visibilidad. Las salas privadas tienen un código de invitación para compartir. LinHug también mantiene salas abiertas de Caza de letras con bots amigables, así que siempre hay una partida disponible.</p>",
        ]],
        ["Consejos para ganar", [
          "<ul><li>Aprende palabras que terminen en letras difíciles para complicarle el turno al siguiente jugador.</li><li>Guarda algunas palabras largas para cada letra: valen más puntos.</li><li>En Caza de letras, busca primero terminaciones comunes y luego reordénalas en palabras más largas.</li><li>No te apresures: una palabra corta y válida es mejor que quedarte sin tiempo.</li></ul>",
        ]],
      ],
      huntTable: ["Longitud de la palabra", "Puntos"],
    },
    notFound: { title: "Página no encontrada — LinHug", h1: "Esta cadena se rompió.", text: "No encontramos esa página. Vuelve al inicio y empieza con una palabra nueva.", button: "Volver a LinHug" },
  },

  pt: {
    locale: "pt_BR",
    paths: { home: "/pt/", howTo: "/pt/como-jogar/" },
    skip: "Pular para o conteúdo",
    nav: [
      ["/pt/#modos", "Modos de jogo"],
      ["/pt/como-jogar/", "Como jogar"],
      ["/pt/#perguntas", "Perguntas"],
    ],
    download: "Baixar",
    themeLabel: "Alternar entre tema claro e escuro",
    name: "Português",
    langMenu: "Escolher idioma",
    homeAria: "Início do LinHug",
    navAria: "Navegação principal",
    footerAria: "Rodapé",
    crumbAria: "Trilha de navegação",
    anchors: { modes: "modos", how: "como", features: "recursos", screens: "telas", videos: "videos", words: "palavras", faq: "perguntas" },
    sky: ["palavra", "magia", "sonho", "oceano", "faísca", "castelo", "eco", "jogar"],
    app: { alternateName: "LinHug Corrente de Palavras", genre: "Jogo de palavras" },
    aside: { title: "Baixe o LinHug", text: "Jogue corrente de palavras ao vivo com seus amigos. Grátis." },
    footer: {
      rights: "© 2026 LinHug. Todos os direitos reservados.",
      social: "Siga o LinHug nas redes sociais",
      followOn: (name) => `Siga o LinHug no ${name}`,
      links: [["/pt/como-jogar/", "Como jogar"], ["/privacy.html", "Política de Privacidade"], ["/terms.html", "Termos de Uso"], [`mailto:${SUPPORT_EMAIL}`, "Suporte"]],
      notice: "O nome, o logotipo, os personagens, os gráficos e áudios, os designs de interface, os textos e o software do LinHug são protegidos pelas leis de propriedade intelectual aplicáveis. Esses materiais não podem ser copiados, adaptados, distribuídos, extraídos ou usados comercialmente sem autorização prévia por escrito.",
    },
    badges: { apple: "Baixar na App Store", google: "Disponível no Google Play", appleAria: "Baixe o LinHug na App Store", googleAria: "Baixe o LinHug no Google Play" },
    home: {
      title: "Jogo de Corrente de Palavras com Amigos — LinHug para iPhone e Android",
      description: "LinHug é um jogo gratuito e multijogador de corrente de palavras. Crie uma sala, convide amigos e siga a última letra. Baixe para iOS e Android.",
      kicker: "Batalhas de palavras multijogador ao vivo",
      h1: "Jogo de corrente de palavras.",
      h1Accent: "Não deixe a corrente quebrar.",
      intro: "LinHug é um jogo de palavras gratuito e multijogador para iPhone e Android. Crie uma sala, convide seus amigos e transforme a última letra de cada palavra na sua próxima jogada. Jogue Corrente clássica, Batalha de palavras ou Caça às letras com palavras em inglês ou turco, com o app todo em português.",
      meta: ["Grátis", "iOS e Android", "App em português"],
      reelAria: "O mascote do LinHug completando o logotipo",
      reelBadge: "Conheça o LinHug",
      modesTitle: "Três jeitos de jogar.",
      modesLead: "Cada sala escolhe um modo, um idioma das palavras e um tempo. Começa tranquilo e termina na disputa.",
      modes: [
        { icon: "∞", title: "Corrente clássica", text: "A corrente de palavras de sempre. Cada palavra deve começar com a última letra da anterior. Se o seu tempo acabar, você sai; o último jogador de pé ganha um bônus de sobrevivência de +20.", tag: "Por turnos" },
        { icon: "⚡", title: "Batalha de palavras", text: "Todos respondem ao mesmo desafio de letra na mesma rodada. Envie uma palavra válida e única antes do tempo acabar; palavras mais longas valem mais pontos.", tag: "Todos jogam" },
        { icon: "★", title: "Caça às letras", text: "Todos recebem as mesmas peças: 8, depois 9 e depois 10 letras. Encontre o máximo de palavras em três rodadas de 45 segundos. Palavras longas valem muitos pontos.", tag: "3 rodadas · 45 segundos" },
      ],
      chainTitle: "Como funciona a corrente de palavras.",
      chainLead: "Uma única regra mantém o jogo andando: sua palavra começa onde a anterior terminou.",
      chain: ["appl<b>e</b>", "elephan<b>t</b>", "tige<b>r</b>", "rocke<b>t</b>", "train"],
      steps: [
        ["Crie ou entre em uma sala", "Entre em uma sala pública ou crie uma privada e compartilhe o código de convite com seus amigos."],
        ["Siga a última letra", "Sua palavra deve começar com a última letra da palavra anterior e precisa estar no dicionário."],
        ["Vença o relógio", "Pense rápido. Palavras repetidas são recusadas e o relógio não para."],
        ["Suba no placar", "Cada letra conta. Vença rodadas, junte pontos e suba no ranking."],
      ],
      howToLink: "Leia todas as regras →",
      featuresTitle: "Um jogo de palavras feito para jogar com amigos.",
      featuresLead: "Fácil de começar, difícil de largar. Cada sala cria uma nova corrente e cada segundo conta.",
      features: [
        { icon: "⌂", title: "Salas privadas", text: "Crie uma sala privada e compartilhe o código. Seus amigos entram por Salas → Entrar com código." },
        { icon: "☺", title: "Seu avatar, seu estilo", text: "Escolha um avatar e um plano de fundo para a sala e leve sua personalidade para cada partida." },
        { icon: "◎", title: "Jogue como convidado", text: "Não precisa criar conta. Se quiser, entre com Apple ou Google para manter seu progresso em outro aparelho." },
      ],
      screensTitle: "Sua aventura de palavras, num relance.",
      screensLead: "Encontre uma sala, defina as regras, aprenda a corrente e dispute com seus amigos o topo do placar.",
      screensAria: "Capturas de tela do app LinHug",
      prev: "Mostrar a captura anterior",
      next: "Mostrar a próxima captura",
      swipe: "Deslize ou use as setas para explorar",
      videosTitle: "Veja o LinHug em ação.",
      videosLead: "Rodadas rápidas, palavras surpreendentes e a energia de manter a corrente viva.",
      videos: [
        ["linhug-gameplay", "Jogue junto", "Convide seus amigos e transforme cada rodada em um desafio multijogador rápido."],
        ["linhug-word-chain", "Deixe as palavras fluírem", "Pense rápido, siga a última letra e mantenha a corrente antes que o tempo acabe."],
        ["linhug-avatar", "Conheça seu avatar", "Escolha seu estilo e leve sua personalidade para cada sala do LinHug."],
        ["linhug-rocket", "Decole no jogo", "Entre em uma sala, comece o desafio e mantenha sua sequência de palavras."],
      ],
      faqTitle: "Perguntas frequentes",
      faq: [
        ["O que é o LinHug?", "LinHug é um jogo gratuito e multijogador de corrente de palavras para iPhone, iPad e Android. Você joga ao vivo contra amigos ou outros jogadores em salas, em turnos, para manter a corrente de palavras."],
        ["Como se joga corrente de palavras?", "Cada jogador diz uma palavra que começa com a última letra da palavra anterior. Por exemplo: apple → elephant → tiger. Não é permitido repetir palavras, elas precisam estar no dicionário e é preciso responder antes do tempo acabar. Veja as <a href=\"/pt/como-jogar/\">regras completas</a>."],
        ["O LinHug é grátis?", "Sim. O LinHug é gratuito para baixar e jogar na App Store e no Google Play."],
        ["Em quais idiomas posso jogar?", "Cada sala escolhe o idioma das palavras: inglês ou turco. O app está disponível em português, inglês, turco, espanhol, indonésio e hindi."],
        ["Posso jogar em privado com amigos?", "Sim. Crie uma sala privada e compartilhe o código de convite. Seus amigos abrem Salas → Entrar com código e digitam o código para entrar."],
        ["Preciso de uma conta?", "Não. Você pode jogar como convidado na hora. Se quiser manter seu progresso em outro aparelho, pode entrar com Apple ou Google."],
        ["O que é Caça às letras?", "Caça às letras é um modo no estilo anagrama. Todos recebem as mesmas peças de letras (8, depois 9 e depois 10) e têm 45 segundos por rodada para encontrar o máximo de palavras. Palavras mais longas valem muito mais pontos."],
      ],
      ctaTitle: "Sua próxima palavra começa aqui.",
      ctaText: "Reúna seus amigos e veja por quanto tempo vocês conseguem manter a corrente viva.",
      ctaIcon: "Ícone do app LinHug",
    },
    howTo: {
      title: "Como Jogar Corrente de Palavras — Regras e Modos do LinHug",
      description: "Aprenda as regras da corrente de palavras: comece pela última letra, vença o relógio e nunca repita palavras. E mais: pontuação da Batalha de palavras e da Caça às letras.",
      crumbs: [["/pt/", "Início"], [null, "Como jogar"]],
      h1: "Como jogar corrente de palavras",
      lead: "A corrente de palavras (também conhecida como jogo da última letra) é um clássico: cada nova palavra precisa começar com a última letra da anterior. O LinHug transforma isso em um jogo multijogador ao vivo, com tempo, três modos e um dicionário que confere cada palavra.",
      sections: [
        ["A regra básica", [
          "<p>O primeiro jogador recebe uma letra inicial. Cada palavra seguinte deve começar com a <strong>última letra da palavra anterior</strong>:</p>",
          "<p class=\"callout\"><strong>apple → elephant → tiger → rocket → train</strong></p>",
          "<ul><li>As palavras precisam estar no dicionário da sala (inglês ou turco).</li><li>Cada palavra só pode ser usada uma vez por partida.</li><li>Você precisa responder antes do tempo da rodada acabar.</li><li>Nomes próprios e abreviações não valem.</li></ul>",
        ]],
        ["Corrente clássica", [
          "<p>Os jogadores jogam em turnos. Cada palavra válida vale <strong>um ponto por letra</strong>, então palavras longas colocam você na frente. Se o seu tempo acabar, você sai da rodada. O último jogador de pé recebe um <strong>bônus de sobrevivência de +20</strong>, e vence quem tiver a maior pontuação total.</p>",
          "<p>Dica: palavras que terminam em letras raras (como <em>x</em>) pressionam o próximo jogador. Quando uma palavra termina em <em>x</em>, o próximo jogador pode começar com qualquer letra.</p>",
        ]],
        ["Batalha de palavras", [
          "<p>Todos jogam ao mesmo tempo. Cada rodada mostra um desafio de letra, e cada jogador envia <strong>uma palavra válida e única</strong> que comece com essa letra antes do tempo acabar. A pontuação depende do tamanho da palavra, então uma palavra longa e rara vence uma curta e rápida.</p>",
        ]],
        ["Caça às letras", [
          "<p>Todos os jogadores recebem as mesmas peças: <strong>8 na primeira rodada, 9 na segunda e 10 na terceira</strong>. Toque nas peças para formar palavras (cada peça uma vez por palavra) e envie o máximo de palavras diferentes em <strong>45 segundos</strong>. As palavras dos adversários ficam ocultas até o fim da rodada.</p>",
          "@@HUNT_TABLE@@",
          "<p>Vence quem tiver a maior pontuação depois de três rodadas. Em caso de empate, a vitória é dividida.</p>",
        ]],
        ["Salas, amigos e bots", [
          "<p>Entre em uma sala pública pela tela Salas ou crie a sua e escolha o modo, o idioma das palavras, o tamanho da sala, o tempo da rodada e a visibilidade. Salas privadas têm um código de convite para compartilhar. O LinHug também mantém salas abertas de Caça às letras com bots amigáveis, então sempre tem uma partida para entrar.</p>",
        ]],
        ["Dicas para vencer", [
          "<ul><li>Aprenda palavras que terminam em letras difíceis para complicar a vez do próximo jogador.</li><li>Guarde algumas palavras longas para cada letra: elas valem mais pontos.</li><li>Na Caça às letras, procure primeiro terminações comuns e depois reorganize em palavras maiores.</li><li>Não entre em pânico: uma palavra curta e válida é melhor do que deixar o tempo acabar.</li></ul>",
        ]],
      ],
      huntTable: ["Tamanho da palavra", "Pontos"],
    },
    notFound: { title: "Página não encontrada — LinHug", h1: "Esta corrente quebrou.", text: "Não encontramos essa página. Volte ao início e comece com uma nova palavra.", button: "Voltar ao LinHug" },
  },

  id: {
    locale: "id_ID",
    paths: { home: "/id/", howTo: "/id/cara-bermain/" },
    skip: "Lewati ke konten",
    nav: [
      ["/id/#mode", "Mode permainan"],
      ["/id/cara-bermain/", "Cara bermain"],
      ["/id/#tanya-jawab", "Tanya jawab"],
    ],
    download: "Unduh",
    themeLabel: "Beralih antara tema terang dan gelap",
    name: "Bahasa Indonesia",
    langMenu: "Pilih bahasa",
    homeAria: "Beranda LinHug",
    navAria: "Navigasi utama",
    footerAria: "Footer",
    crumbAria: "Navigasi halaman",
    anchors: { modes: "mode", how: "cara", features: "fitur", screens: "layar", videos: "video", words: "kata", faq: "tanya-jawab" },
    sky: ["kata", "ajaib", "mimpi", "samudra", "cahaya", "istana", "gema", "main"],
    app: { alternateName: "LinHug Sambung Kata", genre: "Permainan kata" },
    aside: { title: "Unduh LinHug", text: "Main sambung kata secara langsung bersama teman. Gratis." },
    footer: {
      rights: "© 2026 LinHug. Hak cipta dilindungi.",
      social: "Ikuti LinHug di media sosial",
      followOn: (name) => `Ikuti LinHug di ${name}`,
      links: [["/id/cara-bermain/", "Cara bermain"], ["/privacy.html", "Kebijakan Privasi"], ["/terms.html", "Ketentuan Penggunaan"], [`mailto:${SUPPORT_EMAIL}`, "Bantuan"]],
      notice: "Nama, logo, karakter, grafis dan audio, desain antarmuka, teks, serta perangkat lunak LinHug dilindungi oleh undang-undang kekayaan intelektual yang berlaku. Materi ini tidak boleh disalin, diadaptasi, didistribusikan, diekstrak, atau digunakan secara komersial tanpa izin tertulis sebelumnya.",
    },
    badges: { apple: "Unduh di App Store", google: "Dapatkan di Google Play", appleAria: "Unduh LinHug di App Store", googleAria: "Dapatkan LinHug di Google Play" },
    home: {
      title: "Game Sambung Kata Bersama Teman — LinHug untuk iPhone & Android",
      description: "LinHug adalah game sambung kata multipemain gratis. Buat ruangan, undang teman, dan ikuti huruf terakhir. Unduh untuk iOS dan Android.",
      kicker: "Pertarungan kata multipemain secara langsung",
      h1: "Game sambung kata.",
      h1Accent: "Jaga rantainya tetap hidup.",
      intro: "LinHug adalah game kata multipemain gratis untuk iPhone dan Android. Buat ruangan, undang temanmu, dan jadikan huruf terakhir setiap kata sebagai langkah berikutnya. Mainkan Rantai Klasik, Pertarungan Kata, atau Berburu Huruf dengan kata bahasa Inggris atau Turki, dengan aplikasi sepenuhnya dalam bahasa Indonesia.",
      meta: ["Gratis", "iOS & Android", "Aplikasi berbahasa Indonesia"],
      reelAria: "Maskot LinHug melengkapi logo",
      reelBadge: "Kenalan dengan LinHug",
      modesTitle: "Tiga cara bermain.",
      modesLead: "Setiap ruangan memilih mode, bahasa kata, dan waktu. Mulai dengan santai, akhiri dengan seru.",
      modes: [
        { icon: "∞", title: "Rantai Klasik", text: "Sambung kata seperti biasa. Setiap kata harus dimulai dengan huruf terakhir kata sebelumnya. Jika waktumu habis, kamu tersingkir; pemain terakhir yang bertahan mendapat bonus bertahan +20.", tag: "Bergiliran" },
        { icon: "⚡", title: "Pertarungan Kata", text: "Semua pemain menjawab tantangan huruf yang sama di ronde yang sama. Kirim satu kata yang valid dan unik sebelum waktu habis; kata yang lebih panjang dapat poin lebih banyak.", tag: "Semua bermain" },
        { icon: "★", title: "Berburu Huruf", text: "Semua pemain mendapat ubin huruf yang sama: 8, lalu 9, lalu 10. Temukan sebanyak mungkin kata dalam tiga ronde 45 detik. Kata panjang bernilai poin besar.", tag: "3 ronde · 45 detik" },
      ],
      chainTitle: "Cara kerja sambung kata.",
      chainLead: "Satu aturan membuat permainan terus berjalan: katamu dimulai dari huruf akhir kata sebelumnya.",
      chain: ["appl<b>e</b>", "elephan<b>t</b>", "tige<b>r</b>", "rocke<b>t</b>", "train"],
      steps: [
        ["Buat atau gabung ruangan", "Masuk ke ruangan publik, atau buat ruangan privat dan bagikan kode undangan ke temanmu."],
        ["Ikuti huruf terakhir", "Katamu harus dimulai dengan huruf terakhir kata sebelumnya dan harus ada di kamus."],
        ["Kalahkan waktu", "Berpikir cepat. Kata yang diulang ditolak dan waktu terus berjalan."],
        ["Naik di papan skor", "Setiap huruf berarti poin. Menangkan ronde, kumpulkan poin, dan naik peringkat."],
      ],
      howToLink: "Baca semua aturan →",
      featuresTitle: "Game kata yang dibuat untuk bermain bersama teman.",
      featuresLead: "Mudah dimulai, susah berhenti. Setiap ruangan membuat rantai baru dan setiap detik berarti.",
      features: [
        { icon: "⌂", title: "Ruangan privat", text: "Buat ruangan privat dan bagikan kodenya. Temanmu bergabung lewat Ruangan → Gabung dengan kode." },
        { icon: "☺", title: "Avatarmu, gayamu", text: "Pilih avatar dan latar ruangan, lalu bawa kepribadianmu ke setiap pertandingan." },
        { icon: "◎", title: "Main sebagai tamu", text: "Tidak perlu daftar. Jika mau, masuk dengan Apple atau Google agar progresmu tersimpan di perangkat baru." },
      ],
      screensTitle: "Petualangan katamu, sekilas.",
      screensLead: "Temukan ruangan, buat aturan, pelajari rantainya, dan berlomba dengan teman ke puncak papan skor.",
      screensAria: "Tangkapan layar aplikasi LinHug",
      prev: "Tampilkan tangkapan layar sebelumnya",
      next: "Tampilkan tangkapan layar berikutnya",
      swipe: "Geser atau gunakan panah untuk menjelajah",
      videosTitle: "Lihat LinHug beraksi.",
      videosLead: "Ronde cepat, kata-kata mengejutkan, dan serunya menjaga rantai tetap hidup.",
      videos: [
        ["linhug-gameplay", "Main bersama", "Undang temanmu dan jadikan setiap ronde tantangan multipemain yang seru."],
        ["linhug-word-chain", "Biarkan kata mengalir", "Berpikir cepat, ikuti huruf terakhir, dan jaga rantai sebelum waktu habis."],
        ["linhug-avatar", "Kenalan dengan avatarmu", "Pilih gayamu dan bawa kepribadianmu ke setiap ruangan LinHug."],
        ["linhug-rocket", "Meluncur ke permainan", "Masuk ke ruangan, mulai tantangan, dan pertahankan rentetan katamu."],
      ],
      faqTitle: "Pertanyaan yang sering diajukan",
      faq: [
        ["Apa itu LinHug?", "LinHug adalah game sambung kata multipemain gratis untuk iPhone, iPad, dan Android. Kamu bermain langsung melawan teman atau pemain lain di ruangan, bergiliran menjaga rantai kata tetap berjalan."],
        ["Bagaimana cara bermain sambung kata?", "Setiap pemain menyebut kata yang dimulai dengan huruf terakhir kata sebelumnya. Contoh: apple → elephant → tiger. Kata tidak boleh diulang, harus ada di kamus, dan harus dijawab sebelum waktu habis. Lihat <a href=\"/id/cara-bermain/\">aturan lengkapnya</a>."],
        ["Apakah LinHug gratis?", "Ya. LinHug gratis diunduh dan dimainkan di App Store dan Google Play."],
        ["Dalam bahasa apa saya bisa bermain?", "Setiap ruangan memilih bahasa katanya: Inggris atau Turki. Aplikasinya tersedia dalam bahasa Indonesia, Inggris, Turki, Spanyol, Portugis, dan Hindi."],
        ["Bisakah saya bermain secara privat dengan teman?", "Bisa. Buat ruangan privat dan bagikan kode undangannya. Temanmu membuka Ruangan → Gabung dengan kode lalu memasukkan kodenya."],
        ["Apakah saya perlu akun?", "Tidak. Kamu bisa langsung bermain sebagai tamu. Jika ingin menyimpan progres di perangkat lain, kamu bisa masuk dengan Apple atau Google."],
        ["Apa itu Berburu Huruf?", "Berburu Huruf adalah mode bergaya anagram. Semua pemain mendapat ubin huruf yang sama (8, lalu 9, lalu 10) dan punya 45 detik per ronde untuk menemukan sebanyak mungkin kata. Kata yang lebih panjang bernilai jauh lebih banyak poin."],
      ],
      ctaTitle: "Kata berikutnya dimulai di sini.",
      ctaText: "Kumpulkan teman-temanmu dan lihat berapa lama kalian bisa menjaga rantai tetap hidup.",
      ctaIcon: "Ikon aplikasi LinHug",
    },
    howTo: {
      title: "Cara Bermain Sambung Kata — Aturan & Mode Permainan LinHug",
      description: "Pelajari aturan sambung kata: mulai dari huruf terakhir, kalahkan waktu, dan jangan ulangi kata. Plus cara skor Pertarungan Kata dan Berburu Huruf di LinHug.",
      crumbs: [["/id/", "Beranda"], [null, "Cara bermain"]],
      h1: "Cara bermain sambung kata",
      lead: "Sambung kata (juga disebut permainan huruf terakhir) adalah permainan kata klasik: setiap kata baru harus dimulai dengan huruf terakhir kata sebelumnya. LinHug menjadikannya game multipemain langsung dengan pengatur waktu, tiga mode, dan kamus yang memeriksa setiap kata.",
      sections: [
        ["Aturan dasar", [
          "<p>Pemain pertama mendapat huruf awal. Setiap kata berikutnya harus dimulai dengan <strong>huruf terakhir kata sebelumnya</strong>:</p>",
          "<p class=\"callout\"><strong>apple → elephant → tiger → rocket → train</strong></p>",
          "<ul><li>Kata harus ada di kamus ruangan (bahasa Inggris atau Turki).</li><li>Satu kata hanya boleh dipakai sekali per permainan.</li><li>Kamu harus menjawab sebelum waktu ronde habis.</li><li>Nama diri dan singkatan tidak dihitung.</li></ul>",
        ]],
        ["Rantai Klasik", [
          "<p>Pemain bermain bergiliran. Setiap kata valid bernilai <strong>satu poin per huruf</strong>, jadi kata panjang membuatmu unggul. Jika waktumu habis, kamu keluar dari ronde. Pemain terakhir yang bertahan mendapat <strong>bonus bertahan +20</strong>, dan skor total tertinggi yang menang.</p>",
          "<p>Tips: kata yang berakhir dengan huruf langka (seperti <em>x</em>) menekan pemain berikutnya. Jika sebuah kata berakhir dengan <em>x</em>, pemain berikutnya boleh mulai dengan huruf apa saja.</p>",
        ]],
        ["Pertarungan Kata", [
          "<p>Semua pemain bermain bersamaan. Setiap ronde menampilkan satu tantangan huruf, dan setiap pemain mengirim <strong>satu kata yang valid dan unik</strong> yang dimulai dengan huruf itu sebelum waktu habis. Poin dihitung dari panjang kata, jadi kata panjang yang jarang dipakai mengalahkan kata pendek yang cepat.</p>",
        ]],
        ["Berburu Huruf", [
          "<p>Semua pemain mendapat ubin huruf yang sama: <strong>8 di ronde pertama, 9 di ronde kedua, dan 10 di ronde ketiga</strong>. Ketuk ubin untuk menyusun kata (setiap ubin sekali per kata) dan kirim sebanyak mungkin kata berbeda dalam <strong>45 detik</strong>. Kata lawan tersembunyi sampai ronde berakhir.</p>",
          "@@HUNT_TABLE@@",
          "<p>Skor total tertinggi setelah tiga ronde menang. Jika seri, kemenangan dibagi.</p>",
        ]],
        ["Ruangan, teman, dan bot", [
          "<p>Gabung ke ruangan publik dari layar Ruangan, atau buat ruanganmu sendiri dan pilih mode, bahasa kata, ukuran ruangan, waktu ronde, dan visibilitas. Ruangan privat punya kode undangan yang bisa dibagikan. LinHug juga selalu menyediakan ruangan Berburu Huruf terbuka dengan bot yang ramah, jadi selalu ada permainan untuk diikuti.</p>",
        ]],
        ["Tips untuk menang", [
          "<ul><li>Pelajari kata yang berakhir dengan huruf sulit untuk menjebak pemain berikutnya.</li><li>Siapkan beberapa kata panjang untuk setiap huruf: poinnya lebih besar.</li><li>Di Berburu Huruf, cari akhiran umum dulu, lalu susun ulang menjadi kata yang lebih panjang.</li><li>Jangan panik: kata pendek yang valid lebih baik daripada kehabisan waktu.</li></ul>",
        ]],
      ],
      huntTable: ["Panjang kata", "Poin"],
    },
    notFound: { title: "Halaman tidak ditemukan — LinHug", h1: "Rantai ini terputus.", text: "Kami tidak menemukan halaman itu. Kembali ke beranda dan mulai dengan kata baru.", button: "Kembali ke LinHug" },
  },

  hi: {
    locale: "hi_IN",
    paths: { home: "/hi/", howTo: "/hi/kaise-khelein/" },
    skip: "सामग्री पर जाएँ",
    nav: [
      ["/hi/#modes", "गेम मोड"],
      ["/hi/kaise-khelein/", "कैसे खेलें"],
      ["/hi/#faq", "सवाल-जवाब"],
    ],
    download: "डाउनलोड करें",
    themeLabel: "लाइट और डार्क थीम के बीच बदलें",
    name: "हिन्दी",
    langMenu: "भाषा चुनें",
    homeAria: "LinHug होम",
    navAria: "मुख्य नेविगेशन",
    footerAria: "फ़ुटर",
    crumbAria: "पेज पथ",
    anchors: { modes: "modes", how: "how", features: "features", screens: "screens", videos: "videos", words: "words", faq: "faq" },
    sky: ["शब्द", "जादू", "सपना", "सागर", "चमक", "महल", "गूँज", "खेल"],
    app: { alternateName: "LinHug शब्द श्रृंखला", genre: "शब्द गेम" },
    aside: { title: "LinHug डाउनलोड करें", text: "दोस्तों के साथ लाइव वर्ड चेन खेलें। मुफ़्त।" },
    footer: {
      rights: "© 2026 LinHug. सर्वाधिकार सुरक्षित।",
      social: "सोशल मीडिया पर LinHug को फ़ॉलो करें",
      followOn: (name) => `${name} पर LinHug को फ़ॉलो करें`,
      links: [["/hi/kaise-khelein/", "कैसे खेलें"], ["/privacy.html", "गोपनीयता नीति"], ["/terms.html", "उपयोग की शर्तें"], [`mailto:${SUPPORT_EMAIL}`, "सहायता"]],
      notice: "LinHug का नाम, लोगो, पात्र, ग्राफ़िक्स और ऑडियो, इंटरफ़ेस डिज़ाइन, टेक्स्ट और सॉफ़्टवेयर लागू बौद्धिक संपदा कानूनों के तहत सुरक्षित हैं। इन सामग्रियों को पूर्व लिखित अनुमति के बिना कॉपी, रूपांतरित, वितरित, निकाला या व्यावसायिक रूप से उपयोग नहीं किया जा सकता।",
    },
    badges: { apple: "App Store से डाउनलोड करें", google: "Google Play पर पाएँ", appleAria: "App Store से LinHug डाउनलोड करें", googleAria: "Google Play पर LinHug पाएँ" },
    home: {
      title: "दोस्तों के साथ वर्ड चेन गेम — iPhone और Android के लिए LinHug",
      description: "LinHug एक मुफ़्त मल्टीप्लेयर वर्ड चेन गेम है। रूम बनाएँ, दोस्तों को बुलाएँ और आखिरी अक्षर से अगला शब्द बनाएँ। iOS और Android के लिए डाउनलोड करें।",
      kicker: "लाइव मल्टीप्लेयर शब्द मुकाबले",
      h1: "वर्ड चेन गेम।",
      h1Accent: "चेन टूटने न दें।",
      intro: "LinHug iPhone और Android के लिए एक मुफ़्त मल्टीप्लेयर शब्द गेम है। एक रूम बनाएँ, अपने दोस्तों को बुलाएँ और हर शब्द के आखिरी अक्षर को अपनी अगली चाल बनाएँ। क्लासिक चेन, शब्द युद्ध या अक्षर खोज को अंग्रेज़ी या तुर्की शब्दों के साथ खेलें — ऐप पूरी तरह हिन्दी में है।",
      meta: ["मुफ़्त", "iOS और Android", "हिन्दी में ऐप"],
      reelAria: "LinHug का शुभंकर लोगो पूरा करता हुआ",
      reelBadge: "LinHug से मिलें",
      modesTitle: "खेलने के तीन तरीके।",
      modesLead: "हर रूम एक मोड, शब्दों की भाषा और टाइमर चुनता है। शुरुआत आराम से, अंत रोमांचक।",
      modes: [
        { icon: "∞", title: "क्लासिक चेन", text: "पारंपरिक वर्ड चेन। हर शब्द पिछले शब्द के आखिरी अक्षर से शुरू होना चाहिए। समय खत्म हुआ तो आप बाहर; आखिर तक टिकने वाले खिलाड़ी को +20 सर्वाइवल बोनस मिलता है।", tag: "बारी-बारी" },
        { icon: "⚡", title: "शब्द युद्ध", text: "सभी खिलाड़ी एक ही राउंड में एक ही अक्षर की चुनौती का जवाब देते हैं। टाइमर खत्म होने से पहले एक मान्य और अनोखा शब्द भेजें; लंबे शब्दों पर ज़्यादा अंक मिलते हैं।", tag: "सब खेलते हैं" },
        { icon: "★", title: "अक्षर खोज", text: "सबको एक जैसी अक्षर टाइलें मिलती हैं: पहले 8, फिर 9, फिर 10। 45 सेकंड के तीन राउंड में जितने हो सकें उतने शब्द खोजें। लंबे शब्दों पर बड़े अंक मिलते हैं।", tag: "3 राउंड · 45 सेकंड" },
      ],
      chainTitle: "वर्ड चेन कैसे काम करती है।",
      chainLead: "एक ही नियम खेल को आगे बढ़ाता है: आपका शब्द वहीं से शुरू होता है जहाँ पिछला खत्म हुआ।",
      chain: ["appl<b>e</b>", "elephan<b>t</b>", "tige<b>r</b>", "rocke<b>t</b>", "train"],
      steps: [
        ["रूम बनाएँ या जुड़ें", "किसी पब्लिक रूम में जाएँ, या निजी रूम बनाकर आमंत्रण कोड दोस्तों के साथ साझा करें।"],
        ["आखिरी अक्षर का पालन करें", "आपका शब्द पिछले शब्द के आखिरी अक्षर से शुरू होना चाहिए और शब्दकोश में होना चाहिए।"],
        ["टाइमर को हराएँ", "तेज़ी से सोचें। दोहराए गए शब्द स्वीकार नहीं होते और घड़ी चलती रहती है।"],
        ["स्कोरबोर्ड पर चढ़ें", "हर अक्षर गिना जाता है। राउंड जीतें, अंक जुटाएँ और लीडरबोर्ड में ऊपर जाएँ।"],
      ],
      howToLink: "पूरे नियम पढ़ें →",
      featuresTitle: "दोस्तों के लिए बना शब्द गेम।",
      featuresLead: "शुरू करना आसान, छोड़ना मुश्किल। हर रूम में नई चेन बनती है और हर सेकंड मायने रखता है।",
      features: [
        { icon: "⌂", title: "निजी रूम", text: "निजी रूम बनाएँ और कोड साझा करें। आपके दोस्त रूम → कोड से जुड़ें के ज़रिए आपसे जुड़ते हैं।" },
        { icon: "☺", title: "आपका अवतार, आपका अंदाज़", text: "एक अवतार और रूम बैकग्राउंड चुनें, और हर मैच में अपना अंदाज़ लाएँ।" },
        { icon: "◎", title: "मेहमान के रूप में खेलें", text: "साइन-अप की ज़रूरत नहीं। चाहें तो Apple या Google से साइन इन करके अपनी प्रगति नए डिवाइस पर रखें।" },
      ],
      screensTitle: "आपका शब्द रोमांच, एक नज़र में।",
      screensLead: "रूम खोजें, नियम तय करें, चेन सीखें और स्कोरबोर्ड के शीर्ष तक दोस्तों से मुकाबला करें।",
      screensAria: "LinHug ऐप के स्क्रीनशॉट",
      prev: "पिछला स्क्रीनशॉट दिखाएँ",
      next: "अगला स्क्रीनशॉट दिखाएँ",
      swipe: "देखने के लिए स्वाइप करें या तीरों का उपयोग करें",
      videosTitle: "LinHug को चलते हुए देखें।",
      videosLead: "तेज़ राउंड, चौंकाने वाले शब्द और चेन को ज़िंदा रखने का मज़ा।",
      videos: [
        ["linhug-gameplay", "साथ खेलें", "दोस्तों को बुलाएँ और हर राउंड को तेज़ मल्टीप्लेयर चुनौती बनाएँ।"],
        ["linhug-word-chain", "शब्दों को बहने दें", "तेज़ी से सोचें, आखिरी अक्षर का पालन करें और समय खत्म होने से पहले चेन जारी रखें।"],
        ["linhug-avatar", "अपने अवतार से मिलें", "अपना अंदाज़ चुनें और हर LinHug रूम में अपनी पहचान लाएँ।"],
        ["linhug-rocket", "गेम में उड़ान भरें", "रूम में जाएँ, चुनौती शुरू करें और अपनी शब्द लय बनाए रखें।"],
      ],
      faqTitle: "अक्सर पूछे जाने वाले सवाल",
      faq: [
        ["LinHug क्या है?", "LinHug iPhone, iPad और Android के लिए एक मुफ़्त मल्टीप्लेयर वर्ड चेन गेम है। आप रूम में दोस्तों या दूसरे खिलाड़ियों के साथ लाइव खेलते हैं और बारी-बारी से शब्दों की चेन आगे बढ़ाते हैं।"],
        ["वर्ड चेन गेम कैसे खेलते हैं?", "हर खिलाड़ी ऐसा शब्द बोलता है जो पिछले शब्द के आखिरी अक्षर से शुरू हो। उदाहरण: apple → elephant → tiger। शब्द दोहराए नहीं जा सकते, शब्दकोश में होने चाहिए और टाइमर खत्म होने से पहले जवाब देना होता है। <a href=\"/hi/kaise-khelein/\">पूरे नियम</a> देखें।"],
        ["क्या LinHug मुफ़्त है?", "हाँ। LinHug को App Store और Google Play से मुफ़्त में डाउनलोड करके खेला जा सकता है।"],
        ["मैं किन भाषाओं में खेल सकता/सकती हूँ?", "हर रूम अपने शब्दों की भाषा चुनता है: अंग्रेज़ी या तुर्की। ऐप हिन्दी, अंग्रेज़ी, तुर्की, स्पेनिश, पुर्तगाली और इंडोनेशियाई में उपलब्ध है।"],
        ["क्या मैं दोस्तों के साथ निजी रूप से खेल सकता/सकती हूँ?", "हाँ। निजी रूम बनाएँ और उसका आमंत्रण कोड साझा करें। दोस्त रूम → कोड से जुड़ें खोलकर कोड डालते हैं और जुड़ जाते हैं।"],
        ["क्या मुझे अकाउंट चाहिए?", "नहीं। आप तुरंत मेहमान के रूप में खेल सकते हैं। अगर आप अपनी प्रगति दूसरे डिवाइस पर रखना चाहें, तो Apple या Google से साइन इन कर सकते हैं।"],
        ["अक्षर खोज क्या है?", "अक्षर खोज एक एनाग्राम जैसा मोड है। सबको एक जैसी अक्षर टाइलें (8, फिर 9, फिर 10) मिलती हैं और हर राउंड में 45 सेकंड होते हैं ताकि जितने हो सकें उतने शब्द खोजें। लंबे शब्दों पर कहीं ज़्यादा अंक मिलते हैं।"],
      ],
      ctaTitle: "आपका अगला शब्द यहीं से शुरू होता है।",
      ctaText: "दोस्तों को साथ लाएँ और देखें कि आप चेन को कितनी देर तक ज़िंदा रख सकते हैं।",
      ctaIcon: "LinHug ऐप आइकन",
    },
    howTo: {
      title: "वर्ड चेन कैसे खेलें — LinHug के नियम और गेम मोड",
      description: "वर्ड चेन के नियम सीखें: आखिरी अक्षर से शुरू करें, टाइमर को हराएँ और कोई शब्द न दोहराएँ। साथ में LinHug के शब्द युद्ध और अक्षर खोज की स्कोरिंग।",
      crumbs: [["/hi/", "होम"], [null, "कैसे खेलें"]],
      h1: "वर्ड चेन कैसे खेलें",
      lead: "वर्ड चेन (अंत्याक्षरी की तरह आखिरी अक्षर वाला खेल) एक क्लासिक शब्द गेम है: हर नया शब्द पिछले शब्द के आखिरी अक्षर से शुरू होना चाहिए। LinHug इसे टाइमर, तीन मोड और हर शब्द जाँचने वाले शब्दकोश के साथ एक लाइव मल्टीप्लेयर गेम बनाता है।",
      sections: [
        ["बुनियादी नियम", [
          "<p>पहले खिलाड़ी को एक शुरुआती अक्षर मिलता है। उसके बाद हर शब्द <strong>पिछले शब्द के आखिरी अक्षर</strong> से शुरू होना चाहिए:</p>",
          "<p class=\"callout\"><strong>apple → elephant → tiger → rocket → train</strong></p>",
          "<ul><li>शब्द रूम के शब्दकोश (अंग्रेज़ी या तुर्की) में होने चाहिए।</li><li>एक गेम में कोई शब्द केवल एक बार इस्तेमाल हो सकता है।</li><li>राउंड का टाइमर खत्म होने से पहले जवाब देना होता है।</li><li>व्यक्तिवाचक नाम और संक्षिप्त रूप मान्य नहीं हैं।</li></ul>",
        ]],
        ["क्लासिक चेन", [
          "<p>खिलाड़ी बारी-बारी से खेलते हैं। हर मान्य शब्द पर <strong>हर अक्षर के लिए एक अंक</strong> मिलता है, इसलिए लंबे शब्द आपको आगे ले जाते हैं। अगर आपका समय खत्म हो जाए, तो आप राउंड से बाहर हो जाते हैं। आखिर तक टिकने वाले खिलाड़ी को <strong>+20 सर्वाइवल बोनस</strong> मिलता है, और सबसे ज़्यादा कुल अंक वाला जीतता है।</p>",
          "<p>सुझाव: दुर्लभ अक्षरों (जैसे <em>x</em>) पर खत्म होने वाले शब्द अगले खिलाड़ी पर दबाव डालते हैं। जब कोई शब्द <em>x</em> पर खत्म होता है, तो अगला खिलाड़ी किसी भी अक्षर से शुरू कर सकता है।</p>",
        ]],
        ["शब्द युद्ध", [
          "<p>सभी एक साथ खेलते हैं। हर राउंड में एक अक्षर की चुनौती आती है, और हर खिलाड़ी टाइमर खत्म होने से पहले उस अक्षर से शुरू होने वाला <strong>एक मान्य और अनोखा शब्द</strong> भेजता है। अंक शब्द की लंबाई पर आधारित होते हैं, इसलिए लंबा और कम इस्तेमाल होने वाला शब्द छोटे और जल्दी लिखे शब्द से बेहतर है।</p>",
        ]],
        ["अक्षर खोज", [
          "<p>सभी खिलाड़ियों को एक जैसी अक्षर टाइलें मिलती हैं: <strong>पहले राउंड में 8, दूसरे में 9 और तीसरे में 10</strong>। टाइलों पर टैप करके शब्द बनाएँ (हर टाइल एक शब्द में एक बार) और <strong>45 सेकंड</strong> में जितने अलग शब्द हो सकें भेजें। राउंड खत्म होने तक विरोधियों के शब्द छिपे रहते हैं।</p>",
          "@@HUNT_TABLE@@",
          "<p>तीन राउंड के बाद सबसे ज़्यादा कुल अंक वाला जीतता है। बराबरी होने पर जीत साझा होती है।</p>",
        ]],
        ["रूम, दोस्त और बॉट", [
          "<p>रूम स्क्रीन से किसी पब्लिक रूम में जुड़ें, या अपना रूम बनाकर मोड, शब्दों की भाषा, रूम का आकार, राउंड समय और दृश्यता चुनें। निजी रूम को साझा करने के लिए एक आमंत्रण कोड मिलता है। LinHug में दोस्ताना बॉट वाले अक्षर खोज रूम हमेशा खुले रहते हैं, इसलिए खेलने के लिए हमेशा कोई गेम मौजूद रहता है।</p>",
        ]],
        ["जीतने के सुझाव", [
          "<ul><li>मुश्किल अक्षरों पर खत्म होने वाले शब्द सीखें ताकि अगला खिलाड़ी फँस जाए।</li><li>हर अक्षर के लिए कुछ लंबे शब्द याद रखें: उन पर ज़्यादा अंक मिलते हैं।</li><li>अक्षर खोज में पहले आम अंत वाले हिस्से खोजें, फिर उन्हें लंबे शब्दों में बदलें।</li><li>घबराएँ नहीं: समय खत्म होने से बेहतर है एक छोटा पर मान्य शब्द।</li></ul>",
        ]],
      ],
      huntTable: ["शब्द की लंबाई", "अंक"],
    },
    notFound: { title: "पेज नहीं मिला — LinHug", h1: "यह चेन टूट गई।", text: "हमें वह पेज नहीं मिला। होम पर लौटें और नए शब्द से शुरू करें।", button: "LinHug पर लौटें" },
  },
};
